package uz.pdp.appeufloria.enums;

public enum PermissionEnum {
    USER_PERMISSION,

    ATTACHMENT_CREATE,
    ATTACHMENT_DELETE,
    ATTACHMENT_UPDATE,

    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
}
